name: build docker image

on:
    workflow_dispatch: 
    
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
          - name: hello work testing
            run: echo "hello work!!"
