name: build docker image
on:
    workflow_dispatch: 
      inputs:
        run-unit-test:
          description: unit test run for the app
          type: boolean
          required: false
          default: false
        unit-test-file:
          description: unit test file name'
          type: string
          required: true

    push:
      branches: 
        - main   
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
         pip install -r requirements.txt
         pip install coverage
      - name: run unit test
        if: ${{ inputs.run-unit-test == true }}
        run: python -m unittest ${{ inputs.unit-test-file }}
      - name: Run tests with coverage
        run: |
          coverage run -m unittest panda_test.py
          coverage report
          coverage html
      # - name: upload report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-report
      #     path: htmlcov/
      - name: Upload coverage to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: htmlcov/
      - name: Generate coverage badge
        run: |
          pip install pytest pytest-cov coverage-badge
          pytest --cov=my_package tests/
          coverage-badge -o coverage.svg
      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: coverage.svg
      
  
