name: python-panda-app
on:
    workflow_dispatch: 
      inputs:
        run-unit-test:
          description: unit test run for the app
          type: boolean
          required: false
          default: false
        unit-test-file:
          description: unit test file name'
          type: string
          required: true
    push:
      branches: 
        - main
env:
  DOCKER_REGISTRY: asoni007/${{ github.repository }} 
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
         pip install -r requirements.txt
         pip install coverage
      - name: run unit test
        if: ${{ inputs.run-unit-test == true }}
        run: python -m unittest ${{ inputs.unit-test-file }}
      - name: Run tests with coverage
        run: |
          coverage run -m unittest panda_test.py
          coverage report
          coverage html
      - name: upload report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
  docker:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - name: checkin to repo
        uses: actions/checkout@v4

      - name: login to docker_hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: build docker image
        run: docker build -t ${{ env.DOCKER_REGISTRY }}:${{ github.sha }}

      
      
  
