name: build docker image

on:
    push:
        branches:
            - main
    
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
          - name: hello work testing
            run: echo "hello work!!"
