name: Test AWS Role

on:
  push:
      branches: 
        - sandbox
  workflow_run: 
    workflows: [python-panda-app]
    types:
      - completed

jobs:
  deploy-to-sandbox:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_MANAG_ROLE }}
          aws-region: ap-south-1

      - name: test s3 command
        run: aws s3 ls s3://max-pcf-infra-sandbox-bucket001
