name: Deploy

on:
  workflow_run: 
    workflows: [python-panda-app]
    types:
      - completed

jobs:
  deploy:
    
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SANDBOX_ROLE }}
          aws-region: ap-south-1

      - name: test s3 command
        run: aws s3 ls
